import "~/styles/globals.css";

import { ClerkProvider } from '@clerk/nextjs'


import { Inter } from "next/font/google";
import Topnav from "./_components/topnav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by salah yudin",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
      <Topnav/>
      {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
